project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Probability"
  image: "/images/N_Wakim.jpg"
  navbar:
    background: primary
    search: true
    foreground: "#fff"
    collapse-below: sm
    right:
      - syllabus.qmd
      - schedule1.qmd
      - href: class_slides.qmd
        text: Slides
      - href: homeworks.qmd
        text: Homework
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Course Info"
        contents:
          - href: instructors.qmd
            text: Instructors
          - syllabus.qmd
          - schedule1.qmd
      - section: "Course Materials"
        contents:
          - class_slides.qmd
          - href: homeworks.qmd
            text: Homework
          
execute:
  freeze: auto

format:
  html:
    theme:
      - sandstone_NW.scss
    toc: true

editor: visual

