project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Probability"
  navbar:
    background: primary
    search: true
    logo: "images/bsta_550_hex.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: syllabus.qmd
        text: Syllabus
      - schedule1.qmd
      - href: class_slides.qmd
        text: Slides
      - href: homeworks.qmd
        text: Homework
  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - section: "Course Info"
        contents:
          - href: instructors.qmd
            text: Instructors
          - href: syllabus.qmd
            text: Syllabus
          - schedule1.qmd
      - section: "Course Materials"
        contents:
          - class_slides.qmd
          - href: homeworks.qmd
            text: Homework
          - contents: schedule
            href: schedule.qmd
          
execute:
  freeze: auto

format:
  html:
    theme:
      - sandstone_NW.scss
    toc: true

editor: visual

